### ISSUE TITLE
Support R# 9.1

### ISSUE THREAD

**Issue by vfofanov** [MrJul/ForTea#49]
Good day to you!

Do you have plans support R# 9.1 EAP?
Just install VS2015 CTP6  + R#9.1 EAP, but after trying to install ForTea for R#9(some magic with pakages.config), got broken R#. They changed some API, unfortunately

Best regards,
Vasiliy

**Comment by shestakov** [comment]
+1, ~~want~~ need it badly! :)

**Comment by MrJul** [comment]
Sorry for the late response. It's coming :)

**Comment by MrJul** [comment]
v1.3.2 for ReSharper 9.1 is now available!

**Comment by shestakov** [comment]
Thank you, @MrJul! This is a really awesome add-in, I use it to render C# client models to client models for Knockout.js in TypeScript. Have you thought about turning it into a commercially supported product? :)

P.S. Yes, I am worried about possible cancellation of such a good product :)

**Comment by MrJul** [comment]
@shestakov I have no short time plans for it, but knowing that there are potential customers is always nice.

Don't worry, I have absolutely no desire to abandon it either! :)

I was initially planning to support ReSharper 9.1 much earlier, but time flew by!
