### ISSUE TITLE
R# 9.2 support

### ISSUE THREAD

**Issue by shestakov** [MrJul/ForTea#54]
Awaiting as always :)

**Comment by remcoros** [comment]
I tried to upgrade the SDK and compile/deploy this myself, but failed. Resharper extension manager doesn't pick it up from my local source.

Can we get an official update?

**Comment by remcoros** [comment]
Just sent a PR

**Comment by MrJul** [comment]
Sure, sorry for the delay and thank you for the PR, getting back to ForTea dev :)

**Comment by MrJul** [comment]
ForTea for ReSharper 9.2 has been published into the plugins gallery!
In addition, #51 has been fixed.
