### ISSUE TITLE
Requires manual restart in VS2013

### ISSUE THREAD

**Issue by mwpowellhtx** [MrJul/ForTea#57]
Not a major issue, don't know if it is possible to reach out from a plugin to a plugin through to VS2013 in order to restart the host environment. Not the PC itself, just the Visual Studio experience. After that, things like syntax highlighting runs beautifully. Thanks!

**Comment by MrJul** [comment]
There's a required Visual Studio restart each time a ReSharper plugin is installed/updated/uninstalled. ReSharper should tell you this and ask to restart VS, but in v9.x it's not very obvious (an icon in the taskbar). In ReSharper 10, you've got a big yellow bar that you can't miss.

**Comment by mwpowellhtx** [comment]
Thanks, that's probably what it was, though I wasn't paying that close attention.
