### ISSUE TITLE
Cannot install in VS 2013 and ReSharper 10.0.2

### ISSUE THREAD

**Issue by billwoo** [MrJul/ForTea#68]
You provide no information on what exactly you need to select to install ForTea !

I've tried selecting the various folders in the download from ReSharper/Options/ExtensionManager, and, there's no error message, but nothing happens. I do not receive any completion message that asks me to restart Visual Studio. The .tt file I have has no syntax coloring etc.

thanks, Bill

**Comment by MrJul** [comment]
You don't need to go to ReSharper options, click on "Extension Manager" in the main ReSharper menu : a list of all available extensions should be displayed.
