### ISSUE TITLE
it this will support resharp 2016.1 version

### ISSUE THREAD

**Issue by kkman021** [MrJul/ForTea#72]
after install resharp2016.1 version , i can't find fortea on extension manager .
is this will update to support the new version?

**Comment by sjh37** [comment]
I too would like to see support for R# 2016.*

**Comment by LinuxDoku** [comment]
I started porting it to R# 2016.1. There are a lot of changes in R# deamon sdk and I did not find a updated documentation or migration guide yet when I had a quick look on it at my lunch break on monday.

Probably on the weekend, I can dive into this topic again.

**Comment by MrJul** [comment]
Sorry for the delay guys, I was planning to port ForTea to R# 2016.1 next weekend.
@LinuxDoku Thanks for your contribution, I'll be sure to look at your modifications to save time (or accept a PR if you're done before I start).

**Comment by revbones** [comment]
Any update on this?

**Comment by OliverRC** [comment]
+1 to @revbones comment, any news on when we'll be able to use this in 2016.1?

**Comment by MrJul** [comment]
ForTea 1.6.0 [is now available](https://github.com/MrJul/ForTea/releases/tag/v1.6.0) for ReSharper 2016.1!
Thanks to @karpach for the PR.
