### ISSUE TITLE
Relative paths for assemblies

### ISSUE THREAD

**Issue by kennyeni** [MrJul/ForTea#76]
Hi,

If I have a custom DLL (compiled on _projectDLL_) that I want to add to one of my .tt templates on  _projectT4_ (e.g. `<#@ assembly name="MyDLL.dll" #>`)

Everything dependent on this dll is just "red" and I get no intellisense (however, the .tt -> .cs compilation/transformation works fine during MSBuild)

The only way for me to make this work is setting a full path (e.g.. `<#@ assembly name="C:\MyDLL.dll" #>`)

Now, because this dll is actually compiled as part of a dependent project, I'd love to have ForTea automatically recognize the assembly just by referencing the `projectDLL `directly on `projectT4 `.

At this point, however, I'd be fine just setting a _BeforeBuild_ to copy this MyDLL to the .tt folder. (i.e. I can use MSBuild tasks to copy this dll to the .tt folder), but this doesn't work, ForTea doesn't seem (?) to be able to handle Relative paths, I still have to reference the assembly directly (e.g.. `<#@ assembly name="C:\PATH_TO_TT_FILE/MyDLL.dll" #>` )

**Comment by MrJul** [comment]
Hello,

T4 doesn't support relative assembly file names, it's either a GAC strong name or an absolute path, as seen in the [T4 Assembly Directive documentation](https://msdn.microsoft.com/en-us/library/gg586946.aspx).

You can use VS macros instead, eg.
`<#@ assembly name="$(SolutionDir)\YourProject\SomeAssembly.dll" #>`

Hope it helps.

**Comment by kennyeni** [comment]
I see, is there any way to make ForTea recognize the assemblies referenced
directly on the project? It seems like that's my actual case, I was using
the assembly directive, but without effect, as I was using the references

On Wed, Jul 6, 2016 at 12:59 AM, Julien Lebosquain <notifications@github.com

**Comment by MrJul** [comment]
Assemblies are resolved from the project only for Runtime Text Templates (custom tool = `TextTemplatingFilePreprocessor`) since those are directly part of the project. Assembly directives are used for standard ("design time") text templates.
