### ISSUE TITLE
Not supported in Resharper 2016.2

### ISSUE THREAD

**Issue by Kasper888** [MrJul/ForTea#78]
I'm using resharper 2016.2 and cannot find Fortea Resharper Extension Manager.

**Comment by Eagle3386** [comment]
I've managed to download, update and compile ForTea with respect to ReSharper 2016.2.
However, I can't seem to install it into ReSharper - not even by manually editing the configuration files. :(

Any help would be greatly appreciated!

**Comment by JohanLarsson** [comment]
What feed URL do you guys use for 2016.2?
I'm using `https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/Wave_v6.0/`, no idea if it is right.
I can't install ForTea either. 
@MrJul thanks for this nice extension!

**Comment by citizenmatt** [comment]
If you've got it compiled locally, you'll need to update the `.nuspec` so that it takes a dependency on `Wave`, version `[6.0]`. You can add a new source to the extension manager in the options, such as `C:\temp`, and copy the `.nupkg` file there. You should be able to install it now.

**Comment by ac4simms** [comment]
When I do this I get the following:
![image](https://cloud.githubusercontent.com/assets/8781643/18563280/4f345d72-7b44-11e6-8971-40dd165870ef.png)

**Comment by Eagle3386** [comment]
You need to remove dependencies to old (i. e. 104.x) assemblies and add references to newer ones (i. e. 105.x).

**Comment by fakhrulhilal** [comment]
I have problem with dependency to JetBrains.VsIntegration.Shell assembly. Honestly, I really don't know which assemblies are required by this plugin and which assemblies are required by JetBrains latest SDK. What I did:

1. Edit .csproj, removing any line that import project from nuget package folder
2. Remove packages.config file
3. Remove any assembly reference except: System, System.Core, System.Xml

Have any suggestion?

**Comment by MrJul** [comment]
@fakhrulhilal: all `JetBrains.*` assemblies come from the ReSharper SDK. ForTea also uses some additional `Microsoft.VisualStudio.*` assemblies. If you've deleted everything, you need to install the `JetBrains.ReSharper.SDK` and `JetBrains.Platform.VisualStudio` nuget packages.

I've updated the SDK and fixed some errors. I will now run some tests then publish a new release today if everything works. Sorry for the delay.

**Comment by MrJul** [comment]
ForTea is now available for ReSharper 2016.2.
