### ISSUE TITLE
Support R# 2017.* builds

### ISSUE THREAD

**Issue by sjh37** [MrJul/ForTea#82]
Love this extension.
Can you please add support for R# 2017 when you have a moment.
Thanks in advance.

**Comment by ltoshea** [comment]
Also would love to see this

**Comment by Jothay** [comment]
This extension is still not available in 2017.* builds that I can see.

**Comment by MrJul** [comment]
I'm working on it currently, expect a release after R# 2017.1 is released.

**Comment by dmikov** [comment]
It's R# 2017 released. Holding my breath. Seriously counting on you, thank you for great work.

**Comment by MrJul** [comment]
The code in master now compiles and runs on ReSharper 2017.1. There were changes, both in R# SDK (usual expected API changes) and in VS2017 (the required text templating assemblies aren't in the GAC anymore).

However, there's a serious solution leak that I have to fix before I can release it. I'm working on it.

**Comment by MrJul** [comment]
False alarm, this was due to an internal R# window open for debugging purposes, this won't happen in normal use. ForTea 1.9.1 for ReSharper 2017.1 is released.
