### ISSUE TITLE
New version 2017.2 of ReSharper

### ISSUE THREAD

**Issue by OmiCron07** [MrJul/ForTea#85]
Please make the compatibility with the new version of ReSharper 2017.2.

**Comment by matkoch** [comment]
2017.2 I suppose :)

**Comment by OmiCron07** [comment]
Yes, R# 2017.2! With VS2017.3. I updated both today, there the confusion...

**Comment by CzBuCHi** [comment]
i managed to get it working with R# 2017.2 ... ([fork](https://github.com/CzBuCHi/ForTea))

i will make PR after package "JetBrains.Platform.VisualStudio" gets from pre-release version

**Comment by matkoch** [comment]
@CzBuCHi the version you're looking for is `109.0.20170824.131327`.

**Comment by CzBuCHi** [comment]
@matkoch thanks .... there is my pr: #87

**Comment by MrJul** [comment]
ForTea 1.10 for ReSharper 2017.2 is now released.
