### ISSUE TITLE
Not supported in 2017.2

### ISSUE THREAD

**Issue by revbones** [MrJul/ForTea#88]
Could you add support for 2017.2 (I know it's a pain that they break extensions when they update Resharper)

**Comment by AqD** [comment]
I'm trying to migrate the code (zero R# experience). Most parts seem easy but the JetBrains.VsIntegration part is completely gone. Does anyone know where I can look for API / document of the new SDK?

**Comment by remcoros** [comment]
Check https://github.com/MrJul/ForTea/pull/87

I build from that and it works.

**Comment by sdanyliv** [comment]
Any updates here?

**Comment by MrJul** [comment]
ForTea 1.10 for ReSharper 2017.2 is now released.
