### ISSUE TITLE
New Resharper Release 2018

### ISSUE THREAD

**Issue by KCarterSr** [MrJul/ForTea#93]
Could you please update this for the new Resharper release? 2018

Thank you
K. L. Carter Sr.

**Comment by vfrz** [comment]
#94

**Comment by MrJul** [comment]
Sorry for the delay, ForTea is now available for ReSharper 2018.1.1 (there are changes between 2018.1.0 and 2018.1.1 so please ensure you're up-to-date).

**Comment by KCarterSr** [comment]
Thanks soooo... much!
K. Carter Sr.
