### ISSUE TITLE
Support ReSharper 2018.2

### ISSUE THREAD

**Issue by vfofanov** [MrJul/ForTea#97]
Hi!
Could you merge pull request [Update to 2018.2 SDK](https://github.com/MrJul/ForTea/pull/96) to main repo and publish ForTea plugin?

Can't update to new ReSharper without your great plugin))

**Comment by waltnorman** [comment]
Please.  I updated resharper before I knew there wasn't compatible with ForTea.  #sadtrombone

**Comment by mrgfisher** [comment]
Hi @MrJul 

Many thanks for this add-in - its very useful. However,  :-), any chance of an update...

Thanks!

**Comment by KCarterSr** [comment]
Can you pleaseeeees update.
Thank you

**Comment by TheDev6** [comment]
This is the ONLY tolerable t4 plugin IMO! Thanks for writing it, and pretty please hit the latest re-sharper :).

**Comment by gvdkamp** [comment]
Could you _please_ update MrJul?
Thankx

**Comment by ebolefeysot** [comment]
I quite never use this plugin because it is not available for the latest r# version.
Can you unlock it so that we can install it with any r# version ?

**Comment by heikomilke** [comment]
Hi @MrJul
Please

**Comment by MozgC** [comment]
Please! MrJul, save us from pain! :)

**Comment by remcoros** [comment]
ReSharper 2018.3 is in the works, not long until released.

**Comment by tranceporter** [comment]
If all this needs is an approval and the author has no interest in approving it, maybe it's worth doing a fork of this repo and manage it more actively amongst us? Looking at the pull request it's a very minor change, and it should not take ages to get approved. Maybe the original author is super busy or has lost interest? No dis-respect, just thinking of alternatives.

**Comment by zgabi** [comment]
@tranceporter Maybe it is not enough to change only the version number as it is in this PR. Did you see PR #98? The author of that PR mentions that he fixed the compile errors, but it still throws runtime exceptions. So maybe it is not so simple, but I don't know. I did not try to complie it.

**Comment by MrJul** [comment]
I'm planning on working on ForTea for ReSharper 2018.3, but not before 2019.
I haven't been using T4 files much those past months, that's why I've lost some interest (plus little free time). If anyone wants to help, it's gladly welcomed.

**Comment by ac931274** [comment]
I have just created a pull request which compiles and works against R# 2018.3 #99

**Comment by LucaGanio** [comment]
ac931274 can you please publish your version of ForTea on the Resharper gallery, so that we all can use it, since it's pretty clear that MrJul will never do anything about it?

**Comment by ac931274** [comment]
@LucaGanio Hi there, should @MrJul not reply by the end of the month, based on his previous comments about being very busy, I will publish  my version on JetBrains plugin site, with the understanding that it will be taken down as soon as 1) @MrJul takes my pull request or 2) he requests to me that it be taken down.

**Comment by MrJul** [comment]
v1.13.0 for ReSharper 2018.3.2 has (finally) been released!
Many thanks to @ac931274 for the initial changes.

I'm sorry for the delay, I don't think donations will help but I'll try my best to update it faster next time.
I can also add interested people as collaborators to this repository.

**Comment by MrJul** [comment]
The new unified plugin gallery requires approval from JetBrains, so you'll need to wait a bit more for it to become available: https://plugins.jetbrains.com/plugin/11634-fortea
